### ISSUE TITLE
[1.16.5] Mod failed to load

### ISSUE THREAD

**Issue by jengendler** [codetaylor/watercan-1.16#1]
Minecraft: 1.16.5
Forge: 36.0.0 (also tested latest 36.0.42)

Error on load "Caused by 0: java.lang.NoClassDefFoundError: com/codetaylor/mc/athenaeum/util/ConfigHelper"

![2021-02-19_11 26 18](https://user-images.githubusercontent.com/9454003/108551986-8dda5b00-72a5-11eb-9dd7-2f51ae631df2.png)

[crash-2021-02-19_11.25.46-fml.txt](https://github.com/codetaylor/watercan-1.16/files/6012492/crash-2021-02-19_11.25.46-fml.txt)

**Comment by codetaylor** [comment]
Requires https://www.curseforge.com/minecraft/mc-mods/athenaeum-1-16

**Comment by codetaylor** [comment]
Fixed the missing requirement declaration in version `2.0.3`. Forge will now error with a useful message about the dependency not being installed.
