### ISSUE TITLE
1.16.4 and tag at Curseforge

### ISSUE THREAD

**Issue by MJRamon** [codetaylor/watercan-1.16#2]
Does this mod work with 1.16.4? If so, can you please add 1.16.4 tag at Curseforge, so it can be shown in Curseforge app?

**Comment by codetaylor** [comment]
> Does this mod work with 1.16.4?

Oh, probably. Why don't you try it out and let me know.

**Comment by MJRamon** [comment]
So, okey, it works in 1.16.4, yet didn't test on dedicated server.

**Comment by codetaylor** [comment]
Thanks, tagged as 1.16.4.

**Comment by MJRamon** [comment]
Athenaeum should be tagged 1.16.4 too, BTW :)
