### ISSUE TITLE
Watercans not functioning on crops themselves.

### ISSUE THREAD

**Issue by UnicornSnuggler** [codetaylor/watercan-1.16#3]
Holding right-click while targeting a crop yields no functionality from the watercan.  No water particles appear and the watercan's water level does not decrease.  This is true for vanilla crops as well as crops from mods (see Figure A).

Holding right-click while targeting the farmland on which a crop resides causes water particles to appear and the watercan's water level decreases accordingly.  However,  if the watercan's `range` is set to `0`, the crop's growth is not sped up at all (see Figure B).

Expected watercan behavior only transpires on crops when holding right-click while targeting either the farmland on which a crop resides or a block adjacent to a crop with a watercan whose `range` is set to `1` or greater (see Figure C).

_Figure A._
![image](https://user-images.githubusercontent.com/10764837/114959840-734adb00-9e2b-11eb-8330-7f892bf06df3.png)

_Figure B._
![image](https://user-images.githubusercontent.com/10764837/114959969-b9a03a00-9e2b-11eb-910f-8dc569d3f8bb.png)

_Figure C._
![image](https://user-images.githubusercontent.com/10764837/114960163-1bf93a80-9e2c-11eb-9a98-6c990cec18d8.png)

**Comment by codetaylor** [comment]
Can't reproduce this. It works as expected when right-clicking on a crop. It could be a mod conflict, maybe a right-click to harvest mod? Not sure.

**Comment by UnicornSnuggler** [comment]
> Can't reproduce this. It works as expected when right-clicking on a crop. It could be a mod conflict, maybe a right-click to harvest mod? Not sure.

You are absolutely correct.  Looks like this issue is caused by the right-click harvesting setting of `Pam's Harvestcraft 2 - Crops`.
